# Generated by Django 4.0.4 on 2022-05-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_regist_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['FullName'], 'verbose_name': 'Student'},
        ),
    ]
