# Generated by Django 4.0.4 on 2022-05-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_student_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='AddStudent',
        ),
        migrations.AlterModelOptions(
            name='addstudent',
            options={'ordering': ['StudentID'], 'verbose_name': 'Student'},
        ),
    ]
