# Generated by Django 4.0.4 on 2022-05-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_student_addstudent_alter_addstudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addstudent',
            options={'ordering': ['FullName'], 'verbose_name': 'Student'},
        ),
    ]
