# Generated by Django 4.0.4 on 2022-05-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['FullName'], 'verbose_name': 'Contact'},
        ),
    ]
