# Generated by Django 4.0.4 on 2022-05-18 02:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
