# Generated by Django 4.0.4 on 2022-05-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_addstudent_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='Department',
            field=models.CharField(choices=[('General', 'General'), ('Bioinformatics', 'Bioinformatics'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Software Engineering', 'Software Engineering'), ('Decision Support', 'Decision Support'), ('Information Technology', 'Information Technology'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Information System', 'Information System'), ('Computer Science', 'Computer Science')], default='General', max_length=500),
        ),
    ]
