# Generated by Django 4.0.4 on 2022-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_addstudent_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='Department',
            field=models.CharField(choices=[('General', 'General'), ('BIO', 'BIO'), ('DS', 'DS'), ('CS', 'CS'), ('SE', 'SE'), ('IT', 'IT'), ('AI', 'AI'), ('IS', 'IS')], default='General', max_length=500),
        ),
    ]
